name: Project Build
on:
  pull_request:
    branches: [ "develop" ]
  pushes:
    branches: [ "develop" ]

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout-repository
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew build

    - name: Short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk-${{ env.SHORT_SHA }}
        path: app/build/outputs/apk/debug/*.apk